<?php

/**
 * @file
 * Backport of Drupal 8 core filter module improvements.
 */


/**
 * Non-HTML markup language filters that generate HTML.
 */
const FILTER_TYPE_MARKUP_LANGUAGE = 0;

/**
 * HTML tag and attribute restricting filters.
 */
const FILTER_TYPE_HTML_RESTRICTOR = 1;

/**
 * Reversible transformation filters.
 */
const FILTER_TYPE_TRANSFORM_REVERSIBLE = 2;

/**
 * Irreversible transformation filters.
 */
const FILTER_TYPE_TRANSFORM_IRREVERSIBLE = 3;


/**
 * Implements hook_filter_info_alter().
 */
function filter_true_wysiwyg_filter_info_alter(&$info) {
  // There's only one filter in core that limits the allowed tags.
  $info['filter_html']['allowed tags setting'] = 'allowed_html';

  /* CORE */
  if (module_exists('php')) {
    // php.module
    $info['php_code']['type'] = FILTER_TYPE_MARKUP_LANGUAGE;
  }
  // filter.module
  $info['filter_autop'         ]['type'] = FILTER_TYPE_MARKUP_LANGUAGE;
  $info['filter_url'           ]['type'] = FILTER_TYPE_MARKUP_LANGUAGE;
  $info['filter_html_escape'   ]['type'] = FILTER_TYPE_MARKUP_LANGUAGE;
  $info['filter_html'          ]['type'] = FILTER_TYPE_HTML_RESTRICTOR;
  $info['filter_htmlcorrector' ]['type'] = FILTER_TYPE_HTML_RESTRICTOR;

  /* CONTRIB */
  $contrib_filter_type = array(
    // image_resize_filter.module
    'image_resize_filter' => FILTER_TYPE_TRANSFORM_REVERSIBLE,
    'filter_markdown' => FILTER_TYPE_MARKUP_LANGUAGE,
    // typogrify.module
    'typogrify' => FILTER_TYPE_TRANSFORM_IRREVERSIBLE,
  );

  foreach ($contrib_filter_type as $filter => $type) {
    if (empty($info[$filter])) {
      continue;
    }
    $info[$filter]['type'] = $type;
  }
}

/**
 * Identical to check_markup() with the exception of the new ability to *skip*
 * filters that match any filter type in a list of filter types
 *
 * @param array $filter_types_to_skip
 *   (optional) An array of filter types to skip, or an empty array (default)
 *   to skip no filter types. All of the format's filters will be applied,
 *   except for filters of the types that are marked to be skipped.
 *   FILTER_TYPE_HTML_RESTRICTOR is the only type that cannot be skipped.
 *
 * @see aloha.module/aloha_filter_info_alter()
 */
function check_markup2($text, $format_id = NULL, $langcode = '', $cache = FALSE, $filter_types_to_skip = array()) {
  if (!isset($format_id)) {
    $format_id = filter_fallback_format();
  }
  // If the requested text format does not exist, the text cannot be filtered.
  if (!$format = filter_format_load($format_id)) {
    watchdog('filter', 'Missing text format: %format.', array('%format' => $format_id), WATCHDOG_ALERT);
    return '';
  }

  // Prevent FILTER_TYPE_HTML_RESTRICTOR from being skipped.
  if (in_array(FILTER_TYPE_HTML_RESTRICTOR, $filter_types_to_skip)) {
    $filter_types_to_skip = array_diff($filter_types_to_skip, array(FILTER_TYPE_HTML_RESTRICTOR));
  }

  // When certain filters should be skipped, don't perform caching.
  if ($filter_types_to_skip) {
    $cache = FALSE;
  }

  // Check for a cached version of this piece of text.
  $cache = $cache && !empty($format->cache);
  $cache_id = '';
  if ($cache) {
    $cache_id = $format->format . ':' . $langcode . ':' . hash('sha256', $text);
    if ($cached = cache('filter')->get($cache_id)) {
      return $cached->data;
    }
  }

  // Convert all Windows and Mac newlines to a single newline, so filters only
  // need to deal with one possibility.
  $text = str_replace(array("\r\n", "\r"), "\n", $text);

  // Get a complete list of filters, ordered properly.
  $filters = filter_list_format($format->format);
  $filter_info = filter_get_filters();

  // Give filters the chance to escape HTML-like data such as code or formulas.
  foreach ($filters as $name => $filter) {
    // If necessary, skip filters of a certain type.
    if (in_array($filter_info[$name]['type'], $filter_types_to_skip)) {
      continue;
    }
    if ($filter->status && isset($filter_info[$name]['prepare callback']) && function_exists($filter_info[$name]['prepare callback'])) {
      $function = $filter_info[$name]['prepare callback'];
      $text = $function($text, $filter, $format, $langcode, $cache, $cache_id);
    }
  }

  // Perform filtering.
  foreach ($filters as $name => $filter) {
    // If necessary, skip filters of a certain type.
    if (in_array($filter_info[$name]['type'], $filter_types_to_skip)) {
      continue;
    }
    if ($filter->status && isset($filter_info[$name]['process callback']) && function_exists($filter_info[$name]['process callback'])) {
      $function = $filter_info[$name]['process callback'];
      $text = $function($text, $filter, $format, $langcode, $cache, $cache_id);
    }
  }

  // Cache the filtered text. This cache is infinitely valid. It becomes
  // obsolete when $text changes (which leads to a new $cache_id). It is
  // automatically flushed when the text format is updated.
  // @see filter_format_save()
  if ($cache) {
    cache('filter')->set($cache_id, $text);
  }

  return $text;
}

/**
 * @} End of "defgroup filter_modifications".
 */




/**
 * @defgroup filter_wysiwyg Extensions to the Filter API to accommodate "true WYSIWYG" editors.
 * @{
 */

/**
 * Retrieves all filter types that are used in a given text format.
 *
 * @param string $format_id
 *   A text format ID.
 *
 * @return array
 *   All filter types used by filters of a given text format.
 */
function filter_get_filter_types_by_format($format_id) {
  $filter_types = array();

  $filters = filter_list_format($format_id);

  // Ignore filters that are disabled.
  $filters = array_filter($filters, function($filter) {
    return $filter->status;
  });

  $filters_info = filter_get_filters();
  foreach ($filters as $filter) {
    if (!isset($filters_info[$filter->name]['type'])) {
      drupal_set_message(t('Filter !filter has no type specified!', array('!filter' => $filter->name)), 'error');
      continue;
    }

    $filter_types[] = $filters_info[$filter->name]['type'];
  }

  return array_unique($filter_types);
}

/**
 * Retrieve all tags that are allowed by a given text format.
 *
 * @param string $format_id
 *   A text format ID.
 * @return array|TRUE
 *   An array of HTML tags (in "p", not "<p>" format) that are allowed by the
 *   text format. The empty array implies no tags are allowed. TRUE implies all
 *   tags are allowed.
 */
function filter_get_allowed_tags_by_format($format_id) {
  $filters = filter_list_format($format_id);

  // Ignore filters that are disabled or don't have an "allowed tags" setting.
  $filters = array_filter($filters, function($filter) {
    if (!$filter->status) {
      return FALSE;
    }

    $filters_metadata = filter_get_filters();
    if (!empty($filters_metadata[$filter->name]['allowed tags setting'])) {
      return TRUE;
    }
  });

  if (empty($filters)) {
    return TRUE;
  }
  else {
    // From the set of remaining filters (they were filtered by array_filter()
    // above), collect the list of tags that is allowed by *all* filters, i.e.
    // the intersection of all allowed tags.
    $allowed_tags = array_reduce($filters, function($result, $filter) {
      $allowed_tags = array();
      $filters_metadata = filter_get_filters();

      $setting_name = $filters_metadata[$filter->name]['allowed tags setting'];
      $allowed_tags = preg_split('/\s+|<|>/', $filter->settings[$setting_name], -1, PREG_SPLIT_NO_EMPTY);

      // The first filter with an "allowed tags" setting provides the initial
      // set.
      if (!isset($result)) {
        return $allowed_tags;
      }
      // Subsequent filters with an "allowed tags" setting must be intersected
      // with the existing set, to ensure we only end up with the tags that are
      // allowed by *all* filters with an "allowed tags" setting.
      else {
        return array_intersect($result, $allowed_tags);
      }
    }, NULL);

    return $allowed_tags;
  }
}

/**
 * @} End of "defgroup filter_wysiwyg".
 */
